package iinq.functions;

public enum SchemaKeyword {
	PRIMARY_KEY_TYPE,
	PRIMARY_KEY_FIELD,
	PRIMARY_KEY_SIZE,
	NUMBER_OF_RECORDS,
	VALUE_SIZE,
	NUMBER_OF_FIELDS,
	ION_KEY_TYPE,
	FIELD_NAME,
	FIELD_TYPE,
	FIELD_SIZE
}
